### ISSUE TITLE
Redesign Projects page for new content

### ISSUE THREAD

**Issue by karpawich** [GTBitsOfGood/website#62]
# Action Items
- [x] Just steal code the About swoosh + header... don't try to redo the header from scratch
- [x] Re-use CSS / page layout from the About "Roles" section and just change the `justify-content` to `flex-start` for desktop and `flex-center` for mobile

# Mockups
## Reference image
![Project-landing-page](https://user-images.githubusercontent.com/34974152/78952607-2871e700-7aa4-11ea-813b-6fc50ebdf290.jpg)

## Figma mockups (helpful to grab `px` values)
https://www.figma.com/file/aAThxeD86vXciqJRTmDLjyQG/BitsOfGood-web-redesign?node-id=2217%3A44

**Comment by ghost** [comment]
Note: continue using the existing content model for projects until the details pages are done! In the end, we will be moving to a new content model for projects.

Also, once this is done, we should be able to delete the `InfoCard` component for good.
