### ISSUE TITLE
Project details - Key features

### ISSUE THREAD

**Issue by ghost** [GTBitsOfGood/website#70]
**Note:** If you're a new contributor to this repository, refer to [CONTRIBUTING.md](https://github.com/GTBitsOfGood/bog-web/blob/master/CONTRIBUTING.md) before tackling this issue!

**Debug by visiting:** `localhost:3000/projects/mapscout`

Set up sections explaining how the app actually works.

## Design notes
- body font size: `--body-large` on desktop, `--body` on mobile
- "our solution" font size: `30px` (no variable for this)
- leave header sizes to defaults

## Action items
- create a new component under `components/projects` and add it to `routes/projects/[key].svelte`. Pass appropriate Contentful fields as props.
- create each section with images centered on the page.
- note the "user flow" header is hard-coded, while key feature headers come from Contentful. 

## Mockups
**[View on Figma for specifics on sizing variables](https://www.figma.com/file/aAThxeD86vXciqJRTmDLjyQG/BitsOfGood-web-redesign?node-id=3197%3A558)**

## Desktop
<img width="538" alt="image" src="https://user-images.githubusercontent.com/31811199/79055150-a820c280-7c18-11ea-918d-0c0d0c189924.png">

## Mobile
<img width="192" alt="image" src="https://user-images.githubusercontent.com/31811199/79055157-bcfd5600-7c18-11ea-941d-02e8d1e8b499.png">

**Comment by karpawich** [comment]
Header sizes have to be changed on mobile to fit the narrow window width - the feature text was overflowing and it didn't look so hot
