### ISSUE TITLE
New contributors cannot run the website locally

### ISSUE THREAD

**Issue by karpawich** [GTBitsOfGood/website#89]
New contributors currently have to wait for a maintainer in Bits of Good to give them Contentful API keys so they can play around with the website. Ideally, they should just be able to pull down the repo and go without waiting around.

## Action items
- [x] Comment ways that new contributors can easily start playing around with the repo
- [x] Edit this Issue to include the chosen solution below
- [x] Open a PR that adds the solution and removes the [temporary README notice](https://github.com/GTBitsOfGood/bog-web/pull/88)

**Comment by karpawich** [comment]
The Rollup plugin that we use for pulling Contentful data could pull from a JSON file that we include in the repo and populate with sample data when the Contentful API key undefined. If we left any fields in the JSON file empty, the plugin could automatically supply one of the following:

- Strings could be lorem ipsum text
- Images could be taken from https://picsum.photos/width/height where X & Y are the width and height of the images in pixels, respectively.

**Comment by karpawich** [comment]
If the Contentful API token is undefined, @ArkaneMoose 's rollup plugin could pull sample data from a JSON file that we include in the repo. Images can be

**Comment by ghost** [comment]
@karpawich can you do `contentful space export` with Contentful CLI ?
